### ISSUE TITLE
Supported versions of Keycloak

### ISSUE THREAD

**Issue by ahus1** [opdt/keycloak-extension-bundid#8]
Is there a specific minimum / maximum version of Keycloak which should be used with this extension?

Just asking from a Keycloak maintainer's point of view as I assume this would be interesting for potential users of this extension.

**Comment by opdt** [comment]
Hi @ahus1 

we add the supported Major+Minor-Version of Keycloak to our own version in the form Major.Minor.Patch-KeycloakMajor.KeycloakMinor. For example 1.0.0-25.0.

Since Keycloak itself doesnt change the used SPIs that often, older Keycloak versions could work as well.
Right now we don't test that, though.
